// API for BestMing Signatures — fetches from Logic App via backend proxy
// Backend route: GET /api/fiscal/bestming-docs
//
// ── Toggle mock data ────────────────────────────────────────────────────────
// Set USE_MOCK = false when the Logic App backend route is live.
const USE_MOCK = true;
// ────────────────────────────────────────────────────────────────────────────

const FISCAL_API_BASE = '/api/fiscal';

// ─── Mock Dataset ────────────────────────────────────────────────────────────
const MOCK_DATA = [
  { DECLARATION_ID: 1675,  ACTIVECOMPANY: 'DKM_NLD',   TRACESIDENTIFICATION: 'BEST - PRIO',         FISCALCONSIGNEECODE: 'BSN TRADIN',  IMPORTERCODE: 'BSN TRADIN',  IMPORTERCOUNTRY: 'BE', LINKIDERP4: null,    MESSAGESTATUS: 'DMSCLE', PRINCIPAL: ' ',       DATEOFACCEPTANCE: '2024-07-18T00:00:00', PROCESSFACTUURNUMMER: 2008000041, C88NUMMER: 1675  },
  { DECLARATION_ID: 35238, ACTIVECOMPANY: 'DKM_NLD',   TRACESIDENTIFICATION: 'BEST - CMR',           FISCALCONSIGNEECODE: 'DRAGOMOCAB',  IMPORTERCODE: 'DRAGOMOCAB',  IMPORTERCOUNTRY: 'DE', LINKIDERP4: null,    MESSAGESTATUS: 'CREATE', PRINCIPAL: 'VANHOOL', DATEOFACCEPTANCE: '2025-03-04T00:00:00', PROCESSFACTUURNUMMER: 2009000005, C88NUMMER: 35238 },
  { DECLARATION_ID: 1944,  ACTIVECOMPANY: 'DKM_NLD',   TRACESIDENTIFICATION: 'BEST- PRIO',           FISCALCONSIGNEECODE: 'FEDERGLOBA',  IMPORTERCODE: 'FEDERGLOBA',  IMPORTERCOUNTRY: 'BE', LINKIDERP4: null,    MESSAGESTATUS: 'DMSCLE', PRINCIPAL: ' ',       DATEOFACCEPTANCE: '2024-08-14T00:00:00', PROCESSFACTUURNUMMER: 2008000002, C88NUMMER: 1944  },
  { DECLARATION_ID: 2309,  ACTIVECOMPANY: 'DKM_NLD',   TRACESIDENTIFICATION: 'BEST- PRIO',           FISCALCONSIGNEECODE: 'FEDERGLOBA',  IMPORTERCODE: 'FEDERGLOBA',  IMPORTERCOUNTRY: 'BE', LINKIDERP4: null,    MESSAGESTATUS: 'DMSCLE', PRINCIPAL: ' ',       DATEOFACCEPTANCE: '2024-10-01T00:00:00', PROCESSFACTUURNUMMER: 2008000007, C88NUMMER: 2309  },
  { DECLARATION_ID: 3238,  ACTIVECOMPANY: 'LILY_MAAS', TRACESIDENTIFICATION: 'BEST - PRIO - CM.RNL', FISCALCONSIGNEECODE: 'VANCA',       IMPORTERCODE: 'VANCA',       IMPORTERCOUNTRY: 'BE', LINKIDERP4: 'LINK4', MESSAGESTATUS: 'DELETED',PRINCIPAL: ' ',       DATEOFACCEPTANCE: '2024-05-03T07:27:32', PROCESSFACTUURNUMMER: 2008000007, C88NUMMER: 3238  },
  { DECLARATION_ID: 4112,  ACTIVECOMPANY: 'DKM_NLD',   TRACESIDENTIFICATION: 'BEST - PRIO',          FISCALCONSIGNEECODE: 'ALPHATRANS', IMPORTERCODE: 'ALPHATRANS',  IMPORTERCOUNTRY: 'NL', LINKIDERP4: null,    MESSAGESTATUS: 'CREATE', PRINCIPAL: 'SCHENKER',DATEOFACCEPTANCE: '2025-01-10T00:00:00', PROCESSFACTUURNUMMER: 2009000011, C88NUMMER: 4112  },
  { DECLARATION_ID: 4890,  ACTIVECOMPANY: 'DKM_NLD',   TRACESIDENTIFICATION: 'BEST - CMR',           FISCALCONSIGNEECODE: 'GLOBALTRD',  IMPORTERCODE: 'GLOBALTRD',   IMPORTERCOUNTRY: 'FR', LINKIDERP4: null,    MESSAGESTATUS: 'DMSCLE', PRINCIPAL: 'KUEHNE',  DATEOFACCEPTANCE: '2025-02-20T00:00:00', PROCESSFACTUURNUMMER: 2009000014, C88NUMMER: 4890  },
  { DECLARATION_ID: 5033,  ACTIVECOMPANY: 'LILY_MAAS', TRACESIDENTIFICATION: 'BEST - PRIO',          FISCALCONSIGNEECODE: 'BREMERTRD',  IMPORTERCODE: 'BREMERTRD',   IMPORTERCOUNTRY: 'DE', LINKIDERP4: 'LINK2', MESSAGESTATUS: 'CREATE', PRINCIPAL: 'VANHOOL', DATEOFACCEPTANCE: '2025-03-11T00:00:00', PROCESSFACTUURNUMMER: 2009000017, C88NUMMER: 5033  },
  { DECLARATION_ID: 5501,  ACTIVECOMPANY: 'DKM_NLD',   TRACESIDENTIFICATION: 'BEST - PRIO - NL',     FISCALCONSIGNEECODE: 'FEDEX_NL',   IMPORTERCODE: 'FEDEX_NL',    IMPORTERCOUNTRY: 'NL', LINKIDERP4: null,    MESSAGESTATUS: 'DMSCLE', PRINCIPAL: ' ',       DATEOFACCEPTANCE: '2025-01-28T00:00:00', PROCESSFACTUURNUMMER: 2009000009, C88NUMMER: 5501  },
  { DECLARATION_ID: 6044,  ACTIVECOMPANY: 'DKM_NLD',   TRACESIDENTIFICATION: 'BEST - CMR',           FISCALCONSIGNEECODE: 'PANDASHIP',  IMPORTERCODE: 'PANDASHIP',   IMPORTERCOUNTRY: 'BE', LINKIDERP4: null,    MESSAGESTATUS: 'DELETED',PRINCIPAL: 'SCHENKER',DATEOFACCEPTANCE: '2024-11-05T00:00:00', PROCESSFACTUURNUMMER: 2008000019, C88NUMMER: 6044  },
  { DECLARATION_ID: 6712,  ACTIVECOMPANY: 'LILY_MAAS', TRACESIDENTIFICATION: 'BEST - PRIO',          FISCALCONSIGNEECODE: 'ALPHATRANS', IMPORTERCODE: 'ALPHATRANS',  IMPORTERCOUNTRY: 'FR', LINKIDERP4: 'LINK4', MESSAGESTATUS: 'CREATE', PRINCIPAL: 'KUEHNE',  DATEOFACCEPTANCE: '2025-04-01T00:00:00', PROCESSFACTUURNUMMER: 2009000023, C88NUMMER: 6712  },
  { DECLARATION_ID: 7089,  ACTIVECOMPANY: 'DKM_NLD',   TRACESIDENTIFICATION: 'BEST- PRIO',           FISCALCONSIGNEECODE: 'FEDERGLOBA',  IMPORTERCODE: 'FEDERGLOBA',  IMPORTERCOUNTRY: 'BE', LINKIDERP4: null,    MESSAGESTATUS: 'DMSCLE', PRINCIPAL: ' ',       DATEOFACCEPTANCE: '2024-12-19T00:00:00', PROCESSFACTUURNUMMER: 2008000025, C88NUMMER: 7089  },
  { DECLARATION_ID: 7450,  ACTIVECOMPANY: 'DKM_NLD',   TRACESIDENTIFICATION: 'BEST - PRIO',          FISCALCONSIGNEECODE: 'BSN TRADIN',  IMPORTERCODE: 'BSN TRADIN',  IMPORTERCOUNTRY: 'NL', LINKIDERP4: null,    MESSAGESTATUS: 'CREATE', PRINCIPAL: ' ',       DATEOFACCEPTANCE: '2025-04-10T00:00:00', PROCESSFACTUURNUMMER: 2009000028, C88NUMMER: 7450  },
  { DECLARATION_ID: 8001,  ACTIVECOMPANY: 'LILY_MAAS', TRACESIDENTIFICATION: 'BEST - CMR',           FISCALCONSIGNEECODE: 'DRAGOMOCAB',  IMPORTERCODE: 'DRAGOMOCAB',  IMPORTERCOUNTRY: 'DE', LINKIDERP4: 'LINK1', MESSAGESTATUS: 'DMSCLE', PRINCIPAL: 'VANHOOL', DATEOFACCEPTANCE: '2025-02-07T00:00:00', PROCESSFACTUURNUMMER: 2009000031, C88NUMMER: 8001  },
  { DECLARATION_ID: 8345,  ACTIVECOMPANY: 'DKM_NLD',   TRACESIDENTIFICATION: 'BEST - PRIO - CM.RNL', FISCALCONSIGNEECODE: 'GLOBALTRD',   IMPORTERCODE: 'GLOBALTRD',   IMPORTERCOUNTRY: 'FR', LINKIDERP4: null,    MESSAGESTATUS: 'CREATE', PRINCIPAL: 'SCHENKER',DATEOFACCEPTANCE: '2025-03-22T00:00:00', PROCESSFACTUURNUMMER: 2009000035, C88NUMMER: 8345  },
];
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Fetch BestMing documents.
 * Returns mock data when USE_MOCK = true, otherwise calls the Logic App proxy.
 * @returns {Promise<Array>}
 */
export async function getBestmingDocs() {
  if (USE_MOCK) {
    // Simulate network delay so loading states are visible
    await new Promise(r => setTimeout(r, 600));
    return MOCK_DATA;
  }

  const response = await fetch(`${FISCAL_API_BASE}/bestming-docs`, {
    method: 'GET',
    headers: { 'Content-Type': 'application/json' },
  });

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.message || `Failed to fetch BestMing data: ${response.status}`);
  }

  const data = await response.json();
  // Normalize: Logic App returns { Table1: [...] }
  return Array.isArray(data) ? data : (data.Table1 ?? []);
}

/**
 * Send a DocuSign signature request.
 * Payload: { id, principal, processFactuurnummer }
 * @param {{ id: number, principal: string, processFactuurnummer: number }} payload
 * @returns {Promise<Object>}
 */
export async function sendDocuSignRequest(payload) {
  const response = await fetch(`${FISCAL_API_BASE}/bestming-sign`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.message || `DocuSign request failed: ${response.status}`);
  }

  return response.json();
}
